@ECHO OFF
SET "ROOT=%~dp0\.."

:: Compilers
SET COMPILER#=0

REM SET /A COMPILER#=COMPILER#+1
REM SET "PATH[%COMPILER#%]=%ROOT%\build\vs-2013-32"
REM SET "COMPILER[%COMPILER#%]=Visual Studio 12 2013"
REM SET "TOOLSET[%COMPILER#%]="

REM SET /A COMPILER#=COMPILER#+1
REM SET "PATH[%COMPILER#%]=%ROOT%\build\vs-2013-64"
REM SET "COMPILER[%COMPILER#%]=Visual Studio 12 2013 Win64"
REM SET "TOOLSET[%COMPILER#%]=host=x64"

REM SET /A COMPILER#=COMPILER#+1
REM SET "PATH[%COMPILER#%]=%ROOT%\build\vs-2015-32"
REM SET "COMPILER[%COMPILER#%]=Visual Studio 14 2015"
REM SET "TOOLSET[%COMPILER#%]="

REM SET /A COMPILER#=COMPILER#+1
REM SET "PATH[%COMPILER#%]=%ROOT%\build\vs-2015-64"
REM SET "COMPILER[%COMPILER#%]=Visual Studio 14 2015 Win64"
REM SET "TOOLSET[%COMPILER#%]=host=x64"

SET /A COMPILER#=COMPILER#+1
SET "PATH[%COMPILER#%]=%ROOT%\build\vs-2017-32"
SET "COMPILER[%COMPILER#%]=Visual Studio 15 2017"
SET "TOOLSET[%COMPILER#%]="

SET /A COMPILER#=COMPILER#+1
SET "PATH[%COMPILER#%]=%ROOT%\build\vs-2017-64"
SET "COMPILER[%COMPILER#%]=Visual Studio 15 2017 Win64"
SET "TOOLSET[%COMPILER#%]=host=x64"

SET "COMPILER#=%COMPILER#%"